[[MUMPS]]
arch = "aarch64"
git-tree-sha1 = "7f714a408b6decaacbfad4637784249607ce3926"
libgfortran_version = "5.0.0"
os = "macos"

    [[MUMPS.download]]
    sha256 = "7fbdf14a3cb74654a7b2cf9783281614efbd0eb783d6cbc623e617bbf2652997"
    url = "https://github.com/amontoison/MUMPS_seq_jll.jl/releases/download/MUMPS-v5.8.2+1/MUMPS.v5.8.2.aarch64-apple-darwin-libgfortran5.tar.gz"
[[MUMPS]]
arch = "aarch64"
git-tree-sha1 = "97c5bbef740b33255dd917ba351b344414a4f262"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS.download]]
    sha256 = "3dfdafa76067931fbab4727dffa1b3aef7f1cd3bdaff50c7d7b7122f9b903630"
    url = "https://github.com/amontoison/MUMPS_seq_jll.jl/releases/download/MUMPS-v5.8.2+1/MUMPS.v5.8.2.aarch64-linux-gnu-libgfortran5.tar.gz"
[[MUMPS]]
arch = "x86_64"
git-tree-sha1 = "6fdbc0d4397dbc6db91460291cff2d3685e0f138"
libgfortran_version = "5.0.0"
os = "macos"

    [[MUMPS.download]]
    sha256 = "c05a42908e11cee404fd65f9703cb3ef86caee217dbdd2fb13259aa8ff1b1ac9"
    url = "https://github.com/amontoison/MUMPS_seq_jll.jl/releases/download/MUMPS-v5.8.2+1/MUMPS.v5.8.2.x86_64-apple-darwin-libgfortran5.tar.gz"
[[MUMPS]]
arch = "x86_64"
git-tree-sha1 = "4b9ca421bdec8a193ae8fc5bce06369632542467"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS.download]]
    sha256 = "29651d96e366ee99d8ff0c0438f41ee3614546046f0ee4f873edac255b1f2ec9"
    url = "https://github.com/amontoison/MUMPS_seq_jll.jl/releases/download/MUMPS-v5.8.2+1/MUMPS.v5.8.2.x86_64-linux-gnu-libgfortran5.tar.gz"
[[MUMPS]]
arch = "x86_64"
git-tree-sha1 = "be8157abe80de26fdafd37bbb4ea2b0cdb101b43"
libgfortran_version = "5.0.0"
os = "windows"

    [[MUMPS.download]]
    sha256 = "0617252df43ad0cb2dfc6203d9fbe25cae4e3c992dc7e88cd2477864806eae8b"
    url = "https://github.com/amontoison/MUMPS_seq_jll.jl/releases/download/MUMPS-v5.8.2+1/MUMPS.v5.8.2.x86_64-w64-mingw32-libgfortran5.tar.gz"

[[MUMPS_seq]]
arch = "aarch64"
git-tree-sha1 = "84e15acfeaa197821a83e1eb5d893a6024c053bd"
libgfortran_version = "5.0.0"
os = "macos"

    [[MUMPS_seq.download]]
    sha256 = "37fee1a1abe868b3b4e7bb0c00415c181eec6dc45bf350379f4ef2f4287fd1a7"
    url = "https://github.com/amontoison/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.8.0+0/MUMPS_seq.v5.8.0.aarch64-apple-darwin-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "aarch64"
git-tree-sha1 = "7bb60583289bf8bfdcdf67b444d5c6bd0a9c16b2"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "051a4afc52416c368ae07c00ff9294bd967b75cea5acafaddcbb6096b90f5358"
    url = "https://github.com/amontoison/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.8.0+0/MUMPS_seq.v5.8.0.aarch64-linux-gnu-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "7b5adddeef5781e60c92d9cd5aa8da0964050d89"
libgfortran_version = "5.0.0"
os = "macos"

    [[MUMPS_seq.download]]
    sha256 = "bc72e2c9052cc2e8c0c11ccdc24ceb33e1428887bb21c02d511a459dac152bb9"
    url = "https://github.com/amontoison/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.8.0+0/MUMPS_seq.v5.8.0.x86_64-apple-darwin-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "f50d141981daa6308ae593f1a5d7eaf641f13e0f"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "2264ab296a4a60c8c030aaec92f3beeb4c93e927062fd8fb845f245d5ed72400"
    url = "https://github.com/amontoison/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.8.0+0/MUMPS_seq.v5.8.0.x86_64-linux-gnu-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "3b3e95e78781071a75012c1deb5c1fdbbd3849f5"
libgfortran_version = "5.0.0"
os = "windows"

    [[MUMPS_seq.download]]
    sha256 = "5565c08c2ef820b618aa5dd8affcc61d19696560c77fbc5a00fec2f72495c57a"
    url = "https://github.com/amontoison/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.8.0+0/MUMPS_seq.v5.8.0.x86_64-w64-mingw32-libgfortran5.tar.gz"
