[[MUMPS]]
arch = "aarch64"
git-tree-sha1 = "7f714a408b6decaacbfad4637784249607ce3926"
libgfortran_version = "5.0.0"
os = "macos"

    [[MUMPS.download]]
    sha256 = "7fbdf14a3cb74654a7b2cf9783281614efbd0eb783d6cbc623e617bbf2652997"
    url = "https://github.com/amontoison/MUMPS_seq_jll.jl/releases/download/MUMPS-v5.8.2+1/MUMPS.v5.8.2.aarch64-apple-darwin-libgfortran5.tar.gz"
[[MUMPS]]
arch = "aarch64"
git-tree-sha1 = "97c5bbef740b33255dd917ba351b344414a4f262"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS.download]]
    sha256 = "3dfdafa76067931fbab4727dffa1b3aef7f1cd3bdaff50c7d7b7122f9b903630"
    url = "https://github.com/amontoison/MUMPS_seq_jll.jl/releases/download/MUMPS-v5.8.2+1/MUMPS.v5.8.2.aarch64-linux-gnu-libgfortran5.tar.gz"
[[MUMPS]]
arch = "x86_64"
git-tree-sha1 = "6fdbc0d4397dbc6db91460291cff2d3685e0f138"
libgfortran_version = "5.0.0"
os = "macos"

    [[MUMPS.download]]
    sha256 = "c05a42908e11cee404fd65f9703cb3ef86caee217dbdd2fb13259aa8ff1b1ac9"
    url = "https://github.com/amontoison/MUMPS_seq_jll.jl/releases/download/MUMPS-v5.8.2+1/MUMPS.v5.8.2.x86_64-apple-darwin-libgfortran5.tar.gz"
[[MUMPS]]
arch = "x86_64"
git-tree-sha1 = "4b9ca421bdec8a193ae8fc5bce06369632542467"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS.download]]
    sha256 = "29651d96e366ee99d8ff0c0438f41ee3614546046f0ee4f873edac255b1f2ec9"
    url = "https://github.com/amontoison/MUMPS_seq_jll.jl/releases/download/MUMPS-v5.8.2+1/MUMPS.v5.8.2.x86_64-linux-gnu-libgfortran5.tar.gz"
[[MUMPS]]
arch = "x86_64"
git-tree-sha1 = "be8157abe80de26fdafd37bbb4ea2b0cdb101b43"
libgfortran_version = "5.0.0"
os = "windows"

    [[MUMPS.download]]
    sha256 = "0617252df43ad0cb2dfc6203d9fbe25cae4e3c992dc7e88cd2477864806eae8b"
    url = "https://github.com/amontoison/MUMPS_seq_jll.jl/releases/download/MUMPS-v5.8.2+1/MUMPS.v5.8.2.x86_64-w64-mingw32-libgfortran5.tar.gz"

[[MUMPS_seq]]
arch = "aarch64"
git-tree-sha1 = "ce45e99e67fffa140480b3e203600e6b118284e6"
libgfortran_version = "5.0.0"
os = "macos"

    [[MUMPS_seq.download]]
    sha256 = "1f611e1df8dab367982d854678c6eeb370d4102ab2437337b3513b6695c18bc3"
    url = "https://github.com/amontoison/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.8.2+0/MUMPS_seq.v5.8.2.aarch64-apple-darwin-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "aarch64"
git-tree-sha1 = "2590626f4a119ea4aae684b0022a528e7cd178c0"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "a94ed40e6898553be28336573a7fc51243d737c079b86d17d6b670c07b8b713c"
    url = "https://github.com/amontoison/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.8.2+0/MUMPS_seq.v5.8.2.aarch64-linux-gnu-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "5abc90ced3d7829497259aaaa8cb39659f8ca253"
libgfortran_version = "5.0.0"
os = "macos"

    [[MUMPS_seq.download]]
    sha256 = "657053a1f8641e751d95f92a2d48de4312a18f8948fc4bd211e93fb525867737"
    url = "https://github.com/amontoison/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.8.2+0/MUMPS_seq.v5.8.2.x86_64-apple-darwin-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "0eedff61149422bf0567383ce610ffcf67581f29"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MUMPS_seq.download]]
    sha256 = "c4858e7969d2ede3acfb597e638e9549fceb5c0920ce9878b1fd81de3c800b77"
    url = "https://github.com/amontoison/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.8.2+0/MUMPS_seq.v5.8.2.x86_64-linux-gnu-libgfortran5.tar.gz"
[[MUMPS_seq]]
arch = "x86_64"
git-tree-sha1 = "ffea940843c4cc434177c95e99c27fe98102fc85"
libgfortran_version = "5.0.0"
os = "windows"

    [[MUMPS_seq.download]]
    sha256 = "c99b57999763bed911586e724736f9c7a966264814961f0697aa08dcd4bf1b83"
    url = "https://github.com/amontoison/MUMPS_seq_jll.jl/releases/download/MUMPS_seq-v5.8.2+0/MUMPS_seq.v5.8.2.x86_64-w64-mingw32-libgfortran5.tar.gz"
