name = "MUMPS_jll"
uuid = "ca64183c-ec4f-5579-95d5-17e128c21291"
version = "5.8.2+1"

[deps]
JLLWrappers = "692b3bcd-3c85-4b1f-b108-f13ce0eb3210"
CompilerSupportLibraries_jll = "e66e0078-7015-5450-92f7-15fbd957f2ae"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
METIS_jll = "d00139f3-1899-568f-a2f0-47f597d42d70"
OpenBLAS32_jll = "656ef2d0-ae68-5445-9ca0-591084a874a2"
Artifacts = "56f22d72-fd6d-98f1-02f0-08ddc0907c33"

[compat]
JLLWrappers = "1.2.0"
julia = "1.6"
Libdl = "< 0.0.1, 1"
Artifacts = "< 0.0.1, 1"
